include: package:effective_dart/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore
    # Ignore analyzer hints for updating pubspecs when using Future or
    # Stream and not importing dart:async
    # Please see https://github.com/flutter/flutter/pull/24528 for details.
    sdk_version_async_exported_from_core: ignore
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    avoid_single_cascade_in_expression_statements: ignore
    prefer_function_declarations_over_variables: ignore
    prefer_const_constructors_in_immutables: ignore
    sort_pub_dependencies: ignore
  exclude:
    - "bin/cache/**"
    - "lib/i18n/messages_*.dart"
    - "lib/src/http/**"
    - "lib/flavors.dart"
    - "lib/main-*.dart"
    - "lib/generated/**"
    - "lib/generated/intl/**"
    - "lib/net/api.chopper.dart"

linter:
  rules:
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_empty_else
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_void
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - cancel_subscriptions
    - control_flow_in_finally
    - empty_catches
    - empty_statements
    - flutter_style_todos
    - implementation_imports
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - overridden_fields
    - package_names
    - package_prefixed_library_names
    - prefer_asserts_in_initializer_lists
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_inlined_adds
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_void_to_null
    - recursive_getters
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_string_interpolations
    - unrelated_type_equality_checks
    - use_full_hex_values_for_flutter_colors
    - valid_regexps
    - void_checks
